name: Demo matrix.yml

# only one teardown is allowed at a time. If a teardown is
# triggered while a deployment is already in progress, it is queud
concurrency: cicd-datapipelines-dev--nightly-cleanup

on:
  push:
  workflow_dispatch:

jobs:
  # tears down an existing deployment by commit hash
  teardown_deployments:
    # This checks to see if a *deployment tag* was deleted
    strategy:
      matrix:
        hs: [one, two, three]

    name: 'TearDown Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: test secret
        env:
          hs: ${{ matrix.hs }}
          arn: ${{ secrets[matrix.hs] }}
        run: |
          echo $arn && echo $hs
#
    ## needed for OpenID auth with AWS
    #permissions:
      #id-token: write
      #contents: read
#
    ## Information about the event
    #steps:
      #- name: Checkout Repo
        #uses: actions/checkout@v3
#
      #- name: Get short SHA
        #id: slug
        #run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
