name: some func test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Checkout Code
        run: | 
          echo "hello world"
      - name: Checkout Code
        run: |
          python3 ./.github/python-scripts/python-script0.py
      - run: |
          pwd
          ls


